apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgress-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgress-db
  template:
    metadata:
      labels:
        app: postgress-db
    spec:
      volumes:
        - name: postgress-storage
          #asking to use a PVC with the given name
          persistentVolumeClaim:
            claimName: persistent-volumen-claim
      containers:
        - name: postgress-container
          image: postgres
          ports:
            - containerPort: 5432
          imagePullPolicy: Always
          #specifies an environment variable
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                #get the value from the kubernetes secret
                secretKeyRef:
                  #name of the secret object
                  name: secrets
                  #name of the key
                  key: postgres-password
          #bind the PVC to the container data
          volumeMounts:
            #define which folder to be backed up
            - mountPath: /var/lib/postgresql/data
              #define a sub-folder inside PVC to store the data
              subPath: postgres
              #should match the PVC name
              name: postgress-storage
---
#service config
apiVersion: v1
kind: Service
metadata:
  name: postgress-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: postgress-db
  ports:
    - port: 5432
      targetPort: 5432


